#!/bin/sh

# Helper script to start/stop irpweb docker server.

PORT=5000
URI="http://localhost:${PORT}"

if [ "$1" = "on" -o "$1" = "start" ]; then

    # Stop a running server.
    curl -s ${URI}/quit

    # Start a new docker container.
    docker run -p ${PORT}:5000 --rm irpweb/irpweb:latest >& /dev/null &
    echo "You can connect to your server at ${URI}/"

elif [ "$1" = "off" -o "$1" = "stop"  ]; then

    # Stop a running server.
    curl -s ${URI}/quit
    # Exit status will indicate if a server was stopped.

else
    echo "Usage: $0 start|stop" 1>&2
    exit 1
fi
